- hosts: tag_Name_webserver
  tasks:
  - package:
            name: "httpd"
            state: present
  
  - parted:
          device: /dev/xvdh
          number: 1
          state: present
          fs_type: ext4
  
  - filesystem:
          fstype: ext4
          dev: /dev/xvdh
  - mount:
          path: /var/www/html/
          src: /dev/xvdh
          fstype: ext4
          state: mounted
              
  - copy:
            src: "index.html"
            dest: "/var/www/html/"
  - service:
            name: "httpd"
            state: started
            enabled: yes

